default: generateFiles

generateFiles:
		teitorelaxng --odd --apphome=/Users/emmanuelchateau/Documents/informatique/TEIC/Stylesheets/ gdpSchemaTEI.odd.xml ../schema/gdpSchemaTEI.rng; teitohtml --odd  --profile=gdp gdpSchemaTEI.odd.xml gdpSchemaTEIDoc.html;

# --apphome=/Users/emmanuelchateau/Documents/informatique/TEIC/Stylesheets
